Update and rename npm-publish-staging.yml to user-fieldtracking-backend-prod.yml

diff --git a/.github/workflows/user-fieldtracking-backend-prod.yml b/.github/workflows/user-fieldtracking-backend-prod.yml
--- a/.github/workflows/user-fieldtracking-backend-prod.yml
+++ b/.github/workflows/user-fieldtracking-backend-prod.yml
@@ -1,4 +1,4 @@
-name: User fieldtrack Backend Development New
+name: User fieldtrack Backend Production
 
 on:
 
@@ -6,7 +6,7 @@ on:
 
     branches:
 
-      - develop
+      - main
 
 jobs:
 
@@ -20,7 +20,7 @@ jobs:
 
         uses: actions/checkout@v4
 
-      - name: Deploy to Development Server
+      - name: Deploy to Production Server
 
         uses: appleboy/ssh-action@v1.0.3
 
@@ -34,9 +34,9 @@ jobs:
 
           script: |
 
-            echo "Connecting to the Development Server..."
+            echo "Connecting to the Production Server..."
 
-            cd /home/ubuntu/node/user-fieldtracking-backend
+            cd /home/node/user-fieldtracking-backend-prod
 
             echo "Loading NVM..."
 
@@ -50,9 +50,9 @@ jobs:
 
             echo "Pulling latest changes..."
 
-            git checkout develop
+            git checkout main
 
-            git pull origin develop
+            git pull origin main
 
             echo "Installing dependencies..."
 
@@ -66,6 +66,6 @@ jobs:
 
             export PATH=$HOME/.nvm/versions/node/v22/bin:$PATH
 
-            pm2 restart 1 --silent || { echo "PM2 restart failed"; exit 1; }
+            pm2 restart 3 --silent || { echo "PM2 restart failed"; exit 1; }
 
             echo "Development Deployment Completed Successfully!"
